### ISSUE TITLE
UiFlow2.0.bin Update error: 5

### ISSUE THREAD

**Issue by leorrr** [bmorcelli/M5Stick-Launcher#20]
Problems when trying to install **UIFlow2.0.bin**,
**"Update error: 5"**,
any ideas......
Greetings and congratulations for your great work.

**Comment by bmorcelli** [comment]
Hi leorr, thanks for using and enjoying Launcher! I really appreciate this..

This issue occurs due to the partition size of UIFlow applications, it is larger then the OTA partition where Launcher install the applications.. I have an Idea on how to overcome that, so I'm putting it on the list of solutions to implement next week.

Thank you very much for reporting!

**Comment by leorrr** [comment]
Ok, thank you very much, and again congratulations for your work, I will wait patiently,
Greetings Leo...

**Comment by bmorcelli** [comment]
Hello @leorrr 

[Launcher_2_fix_Cardputer.zip](https://github.com/bmorcelli/M5Stick-Launcher/files/15284723/Launcher_2_fix_Cardputer.zip)

Try this test version of the Launcher...

It is pointing to a Test Repo, so the firmwares may be outdated.. it is only for test.. If it is working, I'll publish the release next week

**Comment by leorrr** [comment]
It works very well, error 5 no longer appears and it can be installed after I played for a while on the uiFlow 2 page of m5Stack, and very well, I will continue testing and something comes up, I will let you know.
Thank you.

**Comment by leorrr** [comment]
Bad news....MicroHidra has stopped working, it can be installed but it does not start, the other bins that I have work fine...

**Comment by leorrr** [comment]
Hello, I've been testing the behavior of uiflow2 again and I've realized that despite being usable for making small pieces of code and uploading it through the USB connection, the system doesn't quite work well. The NVS storage (non-volatile storage), where credentials are stored to upload programs to the microcontroller from the cloud, seems to be inaccessible. Also, a menu that usually starts at the beginning to choose the type of connection (web or USB) and list the apps doesn't start either, probably because the NVS is not accessible.
That's a valid perspective. UIFlow is fantastic for teaching programming to beginners, but MicroHydra might be better suited for users who already have some experience and are looking to do something more productive.
I see, maybe it's asking too much of m5Launcher. Anyway, if given the choice, I think I'd prefer compatibility with microHydra over uiflow.
Saludos...

**Comment by bmorcelli** [comment]
Actually the problem with UIFlow is that I couldn't install the vfs storage that cames with the UIFlow, because it comes in a different partition..

I learned how to install spiffs partition though, but this nvs is quite of a challange..

I implemented a way to "erase" the fvs filesystem, so the problem when swapping apps won't happen, but the price for this is losing all data you have saved in the nvs partition, so if you  create a file in microhydra, stored in the flash memory, it will be lost when you install other application.

I was able to connect UIFlow into the computer and make a simple program work.. it doesn't show any fancy boot screen or anything, but works..

test this version and tell me if the problem you reported still exists.

[Launcher_v2_fix_Cardputer.zip](https://github.com/bmorcelli/M5Stick-Launcher/files/15296047/Launcher_v2_fix_Cardputer.zip)

**Comment by leorrr** [comment]
Hello again! I've tried out this new version... UIFLOW2 works, and Microhydra does too. The only detail I suppose you should be aware of is that when you reinstall UIFLOW, the main.py file, if it was there, I guess it's due to the file deletion system NVS, isn't as neat as UIFLOW's exclusive setup, but the truth is that testing UIFLOW without losing the functionality of other applications like MicroHydra is more than satisfactory.

A detail of what happens when the boot.py file is executed.

![m5cardputerUiflow205Thonny](https://github.com/bmorcelli/M5Stick-Launcher/assets/3253546/ff58ebfe-d18e-429f-967c-6c1b262c084c)


Thank you very much, and again congratulations for your work
Greetings Leo...
