### ISSUE TITLE
Cardputer -> Bruce

### ISSUE THREAD

**Issue by VooDooFus** [bmorcelli/M5Stick-Launcher#21]
For me, when installing Bruce off of a SD card, Launcher borks and goes in to a boot loop. Oddly OTA install seems to work fine. /shrug/

(Please keep in mind, I am dumb.)

:)

**Comment by VooDooFus** [comment]
I forgot to mention, the version of Bruce I am using is from m5Burner v3, not github. (Not sure if that matters.)

**Comment by bmorcelli** [comment]
Hey dude,

Have you downloaded this binary from the OTA function? I ask that, because sometimes the file can become corrupted in the download process (ESPs are  not so reliable sometimes..) 

for that, Im sending you the binary, unzip it and copy the .bin into your SD card and try installing. 
[Bruce0.9.zip](https://github.com/bmorcelli/M5Stick-Launcher/files/15280694/Bruce0.9.zip)
